### ISSUE TITLE
How to train without the cuda extension?

### ISSUE THREAD

**Issue by Geek-lixiang** [SHI-Labs/Neighborhood-Attention-Transformer#10]
I can not use the cuda extension, how can I train the model without it?
Thank you very much!

**Comment by alihassanijr** [comment]
Thank you for your interest.
Unfortunately we don't have a cpu version yet. Were you unable to install the extension, or do you not have CUDA?

**Comment by AntonyDrovalov** [comment]
Hello!
Can I run inference without using a cuda extension? (for example, if I have macos operating system)

**Comment by alihassanijr** [comment]
Unfortunately that is not possible at the moment because we don't have a cpu implementation. We plan to release one in the future.

**Comment by AntonyDrovalov** [comment]
> Unfortunately that is not possible at the moment because we don't have a cpu implementation. We plan to release one in the future.

Thanks for reply. Looking forward to this update.

**Comment by Geek-lixiang** [comment]
> 
Thank you very much for your reply.

**Comment by alihassanijr** [comment]
We released the pure PyTorch version (PR #23 ) along with a new version of the kernel.
I'd like to thank @qwopqwop200 for their implementation of our RPB, which was used instead of our own in the PyTorch version.
