### ISSUE TITLE
 Issue with Neighborhood Attention Model (NAT) Pretrained Weights

### ISSUE THREAD

**Issue by Miiitiii** [SHI-Labs/Neighborhood-Attention-Transformer#101]
Dear Mr. Hassani,

I hope this message finds you well.

I am a user of your powerful and highly effective Neighborhood Attention Model (NAT). Firstly, I want to express my gratitude for creating such a helpful model and for your outstanding contributions to the field.

I have been utilizing NAT following the guidelines provided in your GitHub repository, and it has been instrumental in my work. However, after several days of successful usage, I encountered an error regarding the matching of pretrained weights in your model. I have attached a screenshot of this error for your reference. it happens in your latest NATTEN version(natten==0.17.0).

I would greatly appreciate it if you could advise me on how to resolve this issue or if there might be a problem with the model that you could address.

Thank you for your dedication and for all the invaluable work you do. Your assistance in this matter is highly appreciated.

Best regards

![error](https://github.com/SHI-Labs/Neighborhood-Attention-Transformer/assets/39888234/d6d4a6b7-df1d-4445-84c0-8e5140a45aba)

**Comment by alihassanijr** [comment]
Thank you for your interest and apologies for the inconvenience.
This was caused by NATTEN renaming the `bias` argument to `rel_pos_bias` since version `0.17.0`.

I'll start a PR fixing this.
