### ISSUE TITLE
unable to get the pretrain model for classification

### ISSUE THREAD

**Issue by zhou-rui1** [SHI-Labs/Neighborhood-Attention-Transformer#18]
Hi, it seems that the link for the NAT-base classification model is garbled code, could you fix it or send it to me with 563937790@qq.com?

Thanks!

**Comment by alihassanijr** [comment]
Hi, thank you for your interest.
I'm not sure what the issue is, the links work fine for me.
What exactly is the error you observe when you try to use them?

**Comment by zhou-rui1** [comment]
well, when I click the link of eg.[84.3%]， it looks like this:(http://ix.cs.uoregon.edu/~alih/nat/checkpoints/CLS/nat_base.pth)
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/72313540/165442174-7db7ecf3-0579-41bb-9501-ec8c05867710.png">

**Comment by stevenwalton** [comment]
You need to download the file. You can refer to the torch documents for how to utilize this file. https://pytorch.org/tutorials/beginner/saving_loading_models.html
