### ISSUE TITLE
Do you try larger resolution when evaluation or pretrained on ImageNet-22k to get higher performance?

### ISSUE THREAD

**Issue by laisimiao** [SHI-Labs/Neighborhood-Attention-Transformer#39]

**Comment by laisimiao** [comment]
I think it would be more convinced about your model capacity if you provide the mentioned results.

**Comment by alihassanijr** [comment]
As mentioned in the paper, we are currently looking into 22K pretraining. We were facing several issues as Swin did not release their 22k training settings in full until 2 weeks ago, and even now it is still incomplete for reproduction, and training on 22K is time consuming. We plan to release our 22k checkpoints and results when ready, so stay tuned.

**Comment by laisimiao** [comment]
Look forward. Best regards.

**Comment by alihassanijr** [comment]
Regarding this issue, we now have [new models](https://github.com/SHI-Labs/Neighborhood-Attention-Transformer/blob/main/DiNAT.md) which we do train on ImageNet-22K and fine-tune on ImageNet-1K at both 224x224 and 384x384 resolutions.
I'm closing this issue now, but feel free to reopen it if you have further questions.
