### ISSUE TITLE
Downsampling using Overlapping vs non-overlapping Convolutions

### ISSUE THREAD

**Issue by mmaaz60** [SHI-Labs/Neighborhood-Attention-Transformer#4]
Hi,

Congratulations on the great work. I wanted to ask if you have done an ablation on using Overlapping vs Non-Overlapping convolutions for the downsampling layers in NAT. If so, may you share the results?

Thank you

**Comment by alihassanijr** [comment]
Hi,
Thank you for your interest.

Yes we have, it's in the paper already, but it's with the Swin-T configuration. 
If you're referring to NAT-Tiny without overlapping convs, I don't believe we have that yet.

**Comment by alihassanijr** [comment]
I'll close this issue for now due to inactivity, but feel free to reopen it if you have follow-up questions.
