### ISSUE TITLE
how to do Visualization

### ISSUE THREAD

**Issue by skyfallsss** [SHI-Labs/Neighborhood-Attention-Transformer#40]
mmdet show the error NAT is not registered.I can't solve the problem.

**Comment by alihassanijr** [comment]
Hello and thanks for your interest.
Have you followed the instructions on setting up the environment correctly?

**Comment by skyfallsss** [comment]
I can train and test the model successfully,but I want to show the result I tested,such as the painted pictures or the pictures with bounding boxes.

**Comment by alihassanijr** [comment]
We haven't included those scripts, but using them only requires you to move them to the `detection/` directory, and add this line to the python script:

```python3
from nat import *
```

**Comment by skyfallsss** [comment]
I will take a try.Thank you for your help.The output file formed in pickle,how can I use it?

**Comment by skyfallsss** [comment]
In other word,how can I print the bouding box data by using the test script?

**Comment by skyfallsss** [comment]
Thank you for your help.I solved the problem by using `from nat import *`.
