### ISSUE TITLE
Tiny Bug in nattencuda.py

### ISSUE THREAD

**Issue by z-jiaming** [SHI-Labs/Neighborhood-Attention-Transformer#46]
Great Work!

Well, I found a small bug in nattencuda.py.

https://github.com/SHI-Labs/Neighborhood-Attention-Transformer/blob/a9a7580b112a20db48dbc0fc64d25bcd75c974d5/natten/nattencuda.py#L117

it should be self.kernel_size during padding if feature size is small than kernel_size

**Comment by alihassanijr** [comment]
Thank you for your interest, and for bringing this to our attention.
