### ISSUE TITLE
 Where is the Neighborhood Attention 2D?

### ISSUE THREAD

**Issue by ady-yu** [SHI-Labs/Neighborhood-Attention-Transformer#49]
I wonder where is the  Neighborhood Attention 2D.  I can't find the code

**Comment by stevenwalton** [comment]
Our standard NA is by default 2D, so it should be in the [natten folder](https://github.com/SHI-Labs/Neighborhood-Attention-Transformer/tree/main/natten). Unless otherwise specified, NA is 2D.

**Comment by alihassanijr** [comment]
Fixed in PR #55.
