### ISSUE TITLE
abbreviation for rpb

### ISSUE THREAD

**Issue by qsh-zh** [SHI-Labs/Neighborhood-Attention-Transformer#58]
Thanks for your awesome work. 

Can you provide some clues for what is rpb and [apply_pb](https://github.com/SHI-Labs/Neighborhood-Attention-Transformer/blob/1437787fc16bd2ede16e5de6e47beaa4cc0f7ccd/natten/nattentorch2d.py#L43), which does not appear in standard attention? 

Thanks

**Comment by alihassanijr** [comment]
Thank you for your interest.
RPB is relative positional biases, they're learnable biases that are added to attention weights.
They're widely used especially in restricted attention patterns, such as Swin's WSA, and we adopted that into NA.

You can refer to these works for more information.
https://arxiv.org/abs/1711.11575
https://arxiv.org/abs/1904.11491
https://arxiv.org/abs/1910.10683
https://arxiv.org/abs/2002.12804

**Comment by qsh-zh** [comment]
@alihassanijr  thanks for your timely response. 

Thanks for your awesome work!
