### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by yuhaoliu7456** [SHI-Labs/Neighborhood-Attention-Transformer#63]
Hi everyone, does anyone encounter this problem when compiling the code?
--------------
TypeError: forward() missing 1 required positional argument: 'dilation'
-------------

Thanks

**Comment by alihassanijr** [comment]
Thank you for reporting this, we've identified the issue and will be fixing it.

**Comment by yuhaoliu7456** [comment]
Thanks, I will try it again.
