### ISSUE TITLE
About the detail of NATTENQKRPBFunction and NATTENAVFunction

### ISSUE THREAD

**Issue by myt889** [SHI-Labs/Neighborhood-Attention-Transformer#7]
Hi, first congratulations on your great work! I am a newer to Transformer.  I have  successfully installed the NA version of cuda. But when I read your core code about NA, I can not understand the detailed codes of this two functions:NATTENQKRPBFunction and NATTENAVFunction.  Could you explian ? Thank you so much.

**Comment by alihassanijr** [comment]
Hello and thank you for your interest.

Those are Autograd functions, which call the forward and backward pass CUDA kernels. If you like to dig deeper on those, you'd have to refer to the [CUDA kernel](https://github.com/SHI-Labs/Neighborhood-Attention-Transformer/blob/main/classification/cuda/README.md).

**Comment by myt889** [comment]
> Hello and thank you for your interest.
> 
> Those are Autograd functions, which call the forward and backward pass CUDA kernels. If you like to dig deeper on those, you'd have to refer to the [CUDA kernel](https://github.com/SHI-Labs/Neighborhood-Attention-Transformer/blob/main/classification/cuda/README.md).

I got it, thank you so much!
