### ISSUE TITLE
instance segmentation mask2former + dinat

### ISSUE THREAD

**Issue by AM97Y** [SHI-Labs/Neighborhood-Attention-Transformer#97]
Do you have any .py file example of rendering for instance segmentation mask2former + dinat?

**Comment by alihassanijr** [comment]
Thank you for your interest.

If you're referring to a demo script that just dumps the segmentation map, I'm afraid we don't.
But you might find one in [detectron2](https://github.com/facebookresearch/detectron2), the package we used, or the original [Mask2Former](https://github.com/facebookresearch/Mask2Former) repository.
